### ISSUE TITLE
Could you please add a license?

### ISSUE THREAD

**Issue by Ramblurr** [dominicfreeston/freeston-dot-me#3]
Hi there! I love this simple babashka based blog setup. I would like to adapt it for my own needs, but the project doesn't have a license that would permit that.

If you're ok with it, could you please add a free software or other open source license?

**Comment by dominicfreeston** [comment]
Hi @Ramblurr, thanks for asking (and sorry for delayed reply). Glad to hear this could be useful to others - I’m keen to do so but need to figure out best way to do it. I’m definitely happy for the code to be used freely but don’t think I want to necessarily do the same with the content 🤔

**Comment by dominicfreeston** [comment]
Also fwiw @borkdude has [quickblog](https://github.com/borkdude/quickblog) which is already MIT licence and likely to be more robust than mine!

**Comment by dominicfreeston** [comment]
@Ramblurr if it's still of interest, I've added made the generator's source available under MIT (included at the top of each file).
